/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package TrabalhoFinal.view;

import TrabalhoFinal.controller.CelaController;
import TrabalhoFinal.model.CelaModel;
import TrabalhoFinal.model.PresoModel;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author andre
 */
public class CelaView extends javax.swing.JInternalFrame {

    public CelaView() {
        initComponents();
        carregarCelasNoCombo();
        tbPresos.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "ID", "Nome", "Nascimento", "CPF", "Entrada", "Pena", "Filiação", "Naturalidade", "Cor",
                    "Cela Nº", "Capacidade", "Status"
                }
        ));

    }

    private void carregarCelasNoCombo() {
        CelaController controller = new CelaController();
        List<CelaModel> celas = controller.buscarCelas();
        cbCelas.removeAllItems();

        for (CelaModel cela : celas) {
            cbCelas.addItem(cela);
            System.out.println("Celas carregadas: " + celas);

        }
    }

    private void carregarPresosNaTabela(CelaModel celaSelecionada) {
        CelaController controller = new CelaController();
        List<PresoModel> presos = controller.buscarPresosPorCela(celaSelecionada.getNumero());
        DefaultTableModel modelo = (DefaultTableModel) tbPresos.getModel();
        modelo.setRowCount(0);
        for (PresoModel preso : presos) {
            modelo.addRow(new Object[]{
                preso.getIdPreso(),
                preso.getNome(),
                preso.getDataNascimento(),
                preso.getCpf(),
                preso.getDataEntrada(),
                preso.getPena(),
                preso.getFiliacao(),
                preso.getNaturalidade(),
                preso.getCor(),
                celaSelecionada.getNumero(),
                celaSelecionada.getCapacidade(),
                celaSelecionada.getStatus()
            });
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbCelas = new javax.swing.JComboBox<>();
        btCancelarCela = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbPresos = new javax.swing.JTable();

        cbCelas.setModel(new javax.swing.DefaultComboBoxModel<CelaModel>());
        cbCelas.setSelectedItem(new javax.swing.DefaultComboBoxModel<CelaModel>());
        cbCelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCelasActionPerformed(evt);
            }
        });

        btCancelarCela.setText("Cancelar");
        btCancelarCela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarCelaActionPerformed(evt);
            }
        });

        tbPresos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID do Preso", "Nome", "Data de Nascimento", "CPF", "Data da Prisão", "Pena", "Filiação", "Naturalidade", "Cor", "Número da Cela", "Capacidade", "Status da Cela"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbPresos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(cbCelas, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btCancelarCela, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 882, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbCelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCancelarCela))
                .addContainerGap(209, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbCelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCelasActionPerformed
        CelaModel celaSelecionada = (CelaModel) cbCelas.getSelectedItem();
        if (celaSelecionada != null) {
            carregarPresosNaTabela(celaSelecionada);
        }

    }//GEN-LAST:event_cbCelasActionPerformed

    private void btCancelarCelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarCelaActionPerformed
        this.dispose();
    }//GEN-LAST:event_btCancelarCelaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelarCela;
    private javax.swing.JComboBox<CelaModel> cbCelas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbPresos;
    // End of variables declaration//GEN-END:variables
}
