/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package TrabalhoFinal.view;

import TrabalhoFinal.controller.FuncionarioController;
import TrabalhoFinal.model.FuncionarioModel;


/**
 *
 * @author diogo
 */
public class FuncionarioView extends javax.swing.JInternalFrame {

    /**
     * Creates new form FuncionarioView
     */
    public FuncionarioView() {
        initComponents();
        
         tfNomeFunc.setEnabled(false);
        tfCpfFunc.setEnabled(false);
        tfDataNascimentoFunc.setEnabled(false);
        tfRG.setEnabled(false);
        rbMasculino.setEnabled(false);
        rbFeminino.setEnabled(false);
        tfCargo.setEnabled(false);
        tfDataAdmissao.setEnabled(false);
        tfEmail.setEnabled(false);
        tfTelefone.setEnabled(false);
        rbManha.setEnabled(false);
        rbTarde.setEnabled(false);
        rbNoite.setEnabled(false);
        btSalvarFunc.setEnabled(false);
        btLimparFunc.setEnabled(false);
        
    }
public void LimparCampos(){
    tfNomeFunc.setText("");
    tfCpfFunc.setText("");
    tfDataNascimentoFunc.setText("");
    tfRG.setText("");
    rbMasculino.setSelected(false);
    rbFeminino.setSelected(false);
    tfCargo.setText("");
    tfDataAdmissao.setText("");
    tfEmail.setText("");
    tfTelefone.setText("");
    rbManha.setSelected(false);
    rbTarde.setSelected(false);
    rbNoite.setSelected(false);
    

}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbNomeFunc = new javax.swing.JLabel();
        tfNomeFunc = new javax.swing.JTextField();
        lbCpfFunc = new javax.swing.JLabel();
        tfCpfFunc = new javax.swing.JTextField();
        lbDataNascimentoFunc = new javax.swing.JLabel();
        tfDataNascimentoFunc = new javax.swing.JTextField();
        lbtelefone = new javax.swing.JLabel();
        tfTelefone = new javax.swing.JTextField();
        lbEmail = new javax.swing.JLabel();
        tfEmail = new javax.swing.JTextField();
        btFotoPreso = new javax.swing.JButton();
        lbRG = new javax.swing.JLabel();
        tfRG = new javax.swing.JTextField();
        lbNaturaldiade = new javax.swing.JLabel();
        lbCargo = new javax.swing.JLabel();
        tfCargo = new javax.swing.JTextField();
        lbDataAdmissao = new javax.swing.JLabel();
        tfDataAdmissao = new javax.swing.JTextField();
        rbMasculino = new javax.swing.JRadioButton();
        rbFeminino = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        lbCadastroFunc = new javax.swing.JLabel();
        rbManha = new javax.swing.JRadioButton();
        rbTarde = new javax.swing.JRadioButton();
        rbNoite = new javax.swing.JRadioButton();
        btInserirFunc = new javax.swing.JButton();
        btSalvarFunc = new javax.swing.JButton();
        btCancelarFunc = new javax.swing.JButton();
        btLimparFunc = new javax.swing.JButton();

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel3.setText(" SISTEMA PENITENCIÁRIO ");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jLabel3.setOpaque(true);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        lbNomeFunc.setText("Nome:");

        tfNomeFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomeFuncActionPerformed(evt);
            }
        });

        lbCpfFunc.setText("CPF:");

        tfCpfFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCpfFuncActionPerformed(evt);
            }
        });

        lbDataNascimentoFunc.setText("Data de Nascimento:");

        tfDataNascimentoFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDataNascimentoFuncActionPerformed(evt);
            }
        });

        lbtelefone.setText("Telefone");

        tfTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTelefoneActionPerformed(evt);
            }
        });

        lbEmail.setText("Email");

        tfEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEmailActionPerformed(evt);
            }
        });

        btFotoPreso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TrabalhoFinal/view/foto.png"))); // NOI18N
        btFotoPreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFotoPresoActionPerformed(evt);
            }
        });

        lbRG.setText("RG:");

        tfRG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfRGActionPerformed(evt);
            }
        });

        lbNaturaldiade.setText("Sexo:");

        lbCargo.setText("Cargo:");

        lbDataAdmissao.setText("Data de admissão");

        tfDataAdmissao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDataAdmissaoActionPerformed(evt);
            }
        });

        buttonGroup6.add(rbMasculino);
        rbMasculino.setText("Masculino");
        rbMasculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMasculinoActionPerformed(evt);
            }
        });

        buttonGroup6.add(rbFeminino);
        rbFeminino.setText("Feminino");

        jLabel1.setText("Turno:");

        lbCadastroFunc.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        lbCadastroFunc.setText("Cadastro de Funcionário");

        buttonGroup7.add(rbManha);
        rbManha.setText("Manhã");

        buttonGroup7.add(rbTarde);
        rbTarde.setText("Tarde");

        buttonGroup7.add(rbNoite);
        rbNoite.setText("Noite");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(btFotoPreso, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(lbEmail)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tfEmail))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(lbRG)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tfRG))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(lbDataNascimentoFunc)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tfDataNascimentoFunc))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(lbCpfFunc)
                            .addGap(18, 18, 18)
                            .addComponent(tfCpfFunc))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(lbCargo)
                            .addGap(13, 13, 13)
                            .addComponent(tfCargo))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(lbDataAdmissao)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tfDataAdmissao))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(lbtelefone)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tfTelefone))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(lbNomeFunc)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tfNomeFunc)
                                .addComponent(lbCadastroFunc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbNaturaldiade)
                        .addGap(18, 18, 18)
                        .addComponent(rbMasculino)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbFeminino))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(rbManha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbTarde)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbNoite)))
                .addGap(63, 63, 63))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbCadastroFunc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbNomeFunc)
                            .addComponent(tfNomeFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbCpfFunc)
                            .addComponent(tfCpfFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btFotoPreso, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDataNascimentoFunc)
                    .addComponent(tfDataNascimentoFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbRG)
                    .addComponent(tfRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNaturaldiade)
                    .addComponent(rbMasculino)
                    .addComponent(rbFeminino))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCargo)
                    .addComponent(tfCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDataAdmissao)
                    .addComponent(tfDataAdmissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEmail)
                    .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbtelefone)
                    .addComponent(tfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(rbManha)
                    .addComponent(rbTarde)
                    .addComponent(rbNoite))
                .addGap(16, 16, 16))
        );

        btInserirFunc.setText("Inserir");
        btInserirFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInserirFuncActionPerformed(evt);
            }
        });

        btSalvarFunc.setText("Salvar");
        btSalvarFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarFuncActionPerformed(evt);
            }
        });

        btCancelarFunc.setText("Cancelar");
        btCancelarFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarFuncActionPerformed(evt);
            }
        });

        btLimparFunc.setText("Limpar");
        btLimparFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparFuncActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(258, 258, 258)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(132, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btInserirFunc)
                        .addGap(35, 35, 35)
                        .addComponent(btSalvarFunc)
                        .addGap(31, 31, 31)
                        .addComponent(btLimparFunc)
                        .addGap(34, 34, 34)
                        .addComponent(btCancelarFunc)
                        .addGap(105, 105, 105))
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(129, 129, 129))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btInserirFunc)
                    .addComponent(btSalvarFunc)
                    .addComponent(btLimparFunc)
                    .addComponent(btCancelarFunc))
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfNomeFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomeFuncActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomeFuncActionPerformed

    private void tfCpfFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCpfFuncActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCpfFuncActionPerformed

    private void tfDataNascimentoFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDataNascimentoFuncActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDataNascimentoFuncActionPerformed

    private void tfTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTelefoneActionPerformed

    private void tfEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEmailActionPerformed

    private void btFotoPresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFotoPresoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btFotoPresoActionPerformed

    private void tfRGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfRGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfRGActionPerformed

    private void tfDataAdmissaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDataAdmissaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDataAdmissaoActionPerformed

    private void btInserirFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInserirFuncActionPerformed
        tfNomeFunc.setEnabled(true);
        tfCpfFunc.setEnabled(true);
        tfDataNascimentoFunc.setEnabled(true);
        tfRG.setEnabled(true);
        rbMasculino.setEnabled(true);
        rbFeminino.setEnabled(true);
        tfCargo.setEnabled(true);
        tfDataAdmissao.setEnabled(true);
        tfEmail.setEnabled(true);
        tfTelefone.setEnabled(true);
        btSalvarFunc.setEnabled(true);
        btLimparFunc.setEnabled(true);
        btInserirFunc.setEnabled(false);
        rbManha.setEnabled(true);
        rbTarde.setEnabled(true);
        rbNoite.setEnabled(true);
    }//GEN-LAST:event_btInserirFuncActionPerformed

    private void btSalvarFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarFuncActionPerformed
        FuncionarioModel funcionario=new FuncionarioModel();
        String sexo,turno="";
        funcionario.setNomeFunc(tfNomeFunc.getText());
        funcionario.setDataNascimentoFunc(tfDataNascimentoFunc.getText());
        funcionario.setDataAdmissao(tfDataAdmissao.getText());
        funcionario.setCpfFunc(tfCpfFunc.getText());
        funcionario.setEmail(tfEmail.getText());
        funcionario.setRG(tfRG.getText());
        
        if(rbMasculino.isSelected()){
        sexo=rbMasculino.getText();
        }else{
        sexo=rbFeminino.getText();
        }
        
        funcionario.setSexo(sexo);
        funcionario.setCargo(tfCargo.getText());
        
        if(rbManha.isSelected()){
        turno=rbManha.getText();
        }else if(rbTarde.isSelected()){turno=rbTarde.getText();}
        else{turno=rbNoite.getText();}
        
        funcionario.setTelefone(tfTelefone.getText());
        funcionario.setTurno(turno);
        FuncionarioController funcionarioControl=new FuncionarioController();
        funcionarioControl.inserir(funcionario);
        LimparCampos();

        tfNomeFunc.setEnabled(false);
        tfCpfFunc.setEnabled(false);
        tfDataNascimentoFunc.setEnabled(false);
        tfRG.setEnabled(false);
        tfCargo.setEnabled(false);
        tfDataAdmissao.setEnabled(false);
        tfEmail.setEnabled(false);
        tfTelefone.setEnabled(false);
        btSalvarFunc.setEnabled(false);
        btLimparFunc.setEnabled(false);
        btInserirFunc.setEnabled(true);
        rbMasculino.setEnabled(false);
        rbFeminino.setEnabled(false);
        rbManha.setEnabled(false);
        rbTarde.setEnabled(false);
        rbNoite.setEnabled(false);
        rbManha.setSelected(false);
    rbTarde.setSelected(false);
    rbNoite.setSelected(false);
        
    }//GEN-LAST:event_btSalvarFuncActionPerformed

    private void btCancelarFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarFuncActionPerformed

        this.dispose();
    }//GEN-LAST:event_btCancelarFuncActionPerformed

    private void btLimparFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparFuncActionPerformed
        LimparCampos();
    }//GEN-LAST:event_btLimparFuncActionPerformed

    private void rbMasculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMasculinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbMasculinoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelarFunc;
    private javax.swing.JButton btFotoPreso;
    private javax.swing.JButton btInserirFunc;
    private javax.swing.JButton btLimparFunc;
    private javax.swing.JButton btSalvarFunc;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbCadastroFunc;
    private javax.swing.JLabel lbCargo;
    private javax.swing.JLabel lbCpfFunc;
    private javax.swing.JLabel lbDataAdmissao;
    private javax.swing.JLabel lbDataNascimentoFunc;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbNaturaldiade;
    private javax.swing.JLabel lbNomeFunc;
    private javax.swing.JLabel lbRG;
    private javax.swing.JLabel lbtelefone;
    private javax.swing.JRadioButton rbFeminino;
    private javax.swing.JRadioButton rbManha;
    private javax.swing.JRadioButton rbMasculino;
    private javax.swing.JRadioButton rbNoite;
    private javax.swing.JRadioButton rbTarde;
    private javax.swing.JTextField tfCargo;
    private javax.swing.JTextField tfCpfFunc;
    private javax.swing.JTextField tfDataAdmissao;
    private javax.swing.JTextField tfDataNascimentoFunc;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfNomeFunc;
    private javax.swing.JTextField tfRG;
    private javax.swing.JTextField tfTelefone;
    // End of variables declaration//GEN-END:variables

}
