/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TrabalhoFinal.view;

/**
 *
 * @author diogo
 */
public class InicioView extends javax.swing.JFrame {

    /**
     * Creates new form Inicio1View
     */
    
    public InicioView() {
        initComponents();
        setResizable(false);
       
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jDesktopInicio = new javax.swing.JDesktopPane();
        lbTituloInicio = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        JMPreso = new javax.swing.JMenu();
        JMICadastrar = new javax.swing.JMenuItem();
        MIListarPresos = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MICadastrarFunc = new javax.swing.JMenuItem();
        MIListarFunc = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        miConsultarCelas = new javax.swing.JMenuItem();
        JMVisita = new javax.swing.JMenu();
        JMIAgendarVisita = new javax.swing.JMenuItem();
        JMIListar = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbTituloInicio.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        lbTituloInicio.setText(" SISTEMA PENITENCIÁRIO ");
        lbTituloInicio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        lbTituloInicio.setOpaque(true);

        jDesktopInicio.setLayer(lbTituloInicio, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopInicioLayout = new javax.swing.GroupLayout(jDesktopInicio);
        jDesktopInicio.setLayout(jDesktopInicioLayout);
        jDesktopInicioLayout.setHorizontalGroup(
            jDesktopInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopInicioLayout.createSequentialGroup()
                .addContainerGap(271, Short.MAX_VALUE)
                .addComponent(lbTituloInicio)
                .addGap(273, 273, 273))
        );
        jDesktopInicioLayout.setVerticalGroup(
            jDesktopInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopInicioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTituloInicio)
                .addContainerGap(553, Short.MAX_VALUE))
        );

        JMPreso.setText("Preso");

        JMICadastrar.setText("Cadastrar Preso");
        JMICadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMICadastrarActionPerformed(evt);
            }
        });
        JMPreso.add(JMICadastrar);

        MIListarPresos.setText("Listar Presos");
        MIListarPresos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIListarPresosActionPerformed(evt);
            }
        });
        JMPreso.add(MIListarPresos);

        jMenuBar1.add(JMPreso);

        jMenu2.setText("Funcionario");

        MICadastrarFunc.setText("Cadastrar Funcionário");
        MICadastrarFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MICadastrarFuncActionPerformed(evt);
            }
        });
        jMenu2.add(MICadastrarFunc);

        MIListarFunc.setText("Listar Funcionarios");
        MIListarFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIListarFuncActionPerformed(evt);
            }
        });
        jMenu2.add(MIListarFunc);

        jMenuBar1.add(jMenu2);

        jMenu1.setText("Celas");

        miConsultarCelas.setText("Consultar Celas");
        miConsultarCelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miConsultarCelasActionPerformed(evt);
            }
        });
        jMenu1.add(miConsultarCelas);

        jMenuBar1.add(jMenu1);

        JMVisita.setText("Visita");

        JMIAgendarVisita.setText("Agendar Visitas");
        JMIAgendarVisita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMIAgendarVisitaActionPerformed(evt);
            }
        });
        JMVisita.add(JMIAgendarVisita);

        JMIListar.setText("Listar Visitas");
        JMIListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMIListarActionPerformed(evt);
            }
        });
        JMVisita.add(JMIListar);

        jMenuBar1.add(JMVisita);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopInicio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JMICadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMICadastrarActionPerformed
        PresoView preso=new PresoView();
        jDesktopInicio.add(preso);
        preso.setVisible(true);
    }//GEN-LAST:event_JMICadastrarActionPerformed

    private void MICadastrarFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MICadastrarFuncActionPerformed
       FuncionarioView funcionario=new FuncionarioView();
       jDesktopInicio.add(funcionario);
       funcionario.setVisible(true);
    }//GEN-LAST:event_MICadastrarFuncActionPerformed

    private void MIListarPresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIListarPresosActionPerformed
        ListarPresosView listarPresos=new ListarPresosView();
        jDesktopInicio.add(listarPresos);
        listarPresos.setVisible(true);
    }//GEN-LAST:event_MIListarPresosActionPerformed

    private void MIListarFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIListarFuncActionPerformed
       ListarFuncionarioView listarFuncionarios=new ListarFuncionarioView();
       jDesktopInicio.add(listarFuncionarios);
       listarFuncionarios.setVisible(true);
    }//GEN-LAST:event_MIListarFuncActionPerformed

    private void miConsultarCelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConsultarCelasActionPerformed
        CelaView cela=new CelaView();
        jDesktopInicio.add(cela);
        cela.setVisible(true);
    }//GEN-LAST:event_miConsultarCelasActionPerformed

    private void JMIAgendarVisitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMIAgendarVisitaActionPerformed
        VisitaView visitante = new VisitaView();
        jDesktopInicio.add(visitante);
        visitante.setVisible(true);
    }//GEN-LAST:event_JMIAgendarVisitaActionPerformed

    private void JMIListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMIListarActionPerformed
        ListarVisitaView listarVisita = new ListarVisitaView();
        jDesktopInicio.add(listarVisita);
        listarVisita.setVisible(true);
    }//GEN-LAST:event_JMIListarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem JMIAgendarVisita;
    private javax.swing.JMenuItem JMICadastrar;
    private javax.swing.JMenuItem JMIListar;
    private javax.swing.JMenu JMPreso;
    private javax.swing.JMenu JMVisita;
    private javax.swing.JMenuItem MICadastrarFunc;
    private javax.swing.JMenuItem MIListarFunc;
    private javax.swing.JMenuItem MIListarPresos;
    private javax.swing.JDesktopPane jDesktopInicio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel lbTituloInicio;
    private javax.swing.JMenuItem miConsultarCelas;
    // End of variables declaration//GEN-END:variables
}
