

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TrabalhoFinal.view;

/**
 *
 * @author diogo
 */
public class InicioView extends javax.swing.JFrame {

    /**
     * Creates new form Inicio1View
     */
    public InicioView() {
        initComponents();
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopInicio = new javax.swing.JDesktopPane();
        lbTituloInicio = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        JMPreso = new javax.swing.JMenu();
        JMICadastrar = new javax.swing.JMenuItem();
        JMIAgendar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbTituloInicio.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        lbTituloInicio.setText(" SISTEMA PENITENCIÁRIO ");
        lbTituloInicio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        lbTituloInicio.setOpaque(true);

        jDesktopInicio.setLayer(lbTituloInicio, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopInicioLayout = new javax.swing.GroupLayout(jDesktopInicio);
        jDesktopInicio.setLayout(jDesktopInicioLayout);
        jDesktopInicioLayout.setHorizontalGroup(
            jDesktopInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopInicioLayout.createSequentialGroup()
                .addGap(218, 218, 218)
                .addComponent(lbTituloInicio)
                .addContainerGap(221, Short.MAX_VALUE))
        );
        jDesktopInicioLayout.setVerticalGroup(
            jDesktopInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopInicioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTituloInicio)
                .addContainerGap(480, Short.MAX_VALUE))
        );

        JMPreso.setText("Preso");

        JMICadastrar.setText("Cadastrar Preso");
        JMICadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMICadastrarActionPerformed(evt);
            }
        });
        JMPreso.add(JMICadastrar);

        JMIAgendar.setText("Agendar visitas");
        JMPreso.add(JMIAgendar);

        jMenuBar1.add(JMPreso);

        jMenu2.setText("Funcionario");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopInicio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopInicio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JMICadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMICadastrarActionPerformed
        PresoView preso=new PresoView();
        jDesktopInicio.add(preso);
        preso.setVisible(true);
    }//GEN-LAST:event_JMICadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem JMIAgendar;
    private javax.swing.JMenuItem JMICadastrar;
    private javax.swing.JMenu JMPreso;
    private javax.swing.JDesktopPane jDesktopInicio;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lbTituloInicio;
    // End of variables declaration//GEN-END:variables
}
