/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package TrabalhoFinal.view;

import TrabalhoFinal.controller.PresoController;
import TrabalhoFinal.model.PresoModel;
import java.util.List;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuário
 */
public class ListarPresosView extends javax.swing.JInternalFrame {

    /**
     * Creates new form ListarPresosView
     */
    public ListarPresosView() {
        initComponents();
    }
    
    public void listarOsCara(){
    List<PresoModel>listarPreso=new PresoController().listar();
       DefaultTableModel modelo=(DefaultTableModel)JTPreso.getModel();
       modelo.setRowCount(0);
       for(PresoModel preso: listarPreso){
       modelo.addRow(new Object[]{
       preso.getNome(),
       preso.getCpf(),
       preso.getDataNascimento(),
       preso.getFiliacao(),
       preso.getNaturalidade(),
       preso.getCor(),
       preso.getDataEntrada(),
       preso.getPena(),
       preso.getIdCela(),
       preso.getIdPreso()
       });
}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        JTPreso = new javax.swing.JTable();
        btListarPresos = new javax.swing.JButton();
        btEditarPresos = new javax.swing.JButton();
        btExcluirPresos = new javax.swing.JButton();
        btCancelarListarPreso = new javax.swing.JButton();

        JTPreso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "CPF", "Data de nascimento", "Nome da mãe", "Naturalidade", "Cor", "Data de prisão", "Pena", "Numero da cela", "Id"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JTPreso.setShowGrid(true);
        jScrollPane1.setViewportView(JTPreso);

        btListarPresos.setText("Listar Presos");
        btListarPresos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btListarPresosActionPerformed(evt);
            }
        });

        btEditarPresos.setText("Editar Presos");
        btEditarPresos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarPresosActionPerformed(evt);
            }
        });

        btExcluirPresos.setText("Excluir Presos");
        btExcluirPresos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirPresosActionPerformed(evt);
            }
        });

        btCancelarListarPreso.setText("Cancelar");
        btCancelarListarPreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarListarPresoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 887, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(btListarPresos)
                .addGap(134, 134, 134)
                .addComponent(btEditarPresos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btExcluirPresos)
                .addGap(150, 150, 150)
                .addComponent(btCancelarListarPreso)
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btExcluirPresos)
                    .addComponent(btEditarPresos)
                    .addComponent(btListarPresos)
                    .addComponent(btCancelarListarPreso))
                .addGap(0, 257, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btEditarPresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarPresosActionPerformed
         int selecionada=JTPreso.getSelectedRow();
         if(selecionada!=-1){
         PresoModel presoModelo=new PresoModel();
         
        presoModelo.setNome(JTPreso.getValueAt(selecionada, 0).toString());
        presoModelo.setCpf(JTPreso.getValueAt(selecionada, 1).toString());
        presoModelo.setDataNascimento(JTPreso.getValueAt(selecionada, 2).toString());
        presoModelo.setFiliacao(JTPreso.getValueAt(selecionada, 3).toString());
        presoModelo.setNaturalidade(JTPreso.getValueAt(selecionada, 4).toString());
        presoModelo.setCor(JTPreso.getValueAt(selecionada, 5).toString());
        presoModelo.setDataEntrada(JTPreso.getValueAt(selecionada, 6).toString());
        presoModelo.setPena(JTPreso.getValueAt(selecionada, 7).toString());
        presoModelo.setIdCela(Integer.parseInt(JTPreso.getValueAt(selecionada, 8).toString()));
        presoModelo.setIdPreso(Integer.parseInt(JTPreso.getValueAt(selecionada, 9).toString()));
        PresoView presoVW=new PresoView();
        presoVW.ativarSalvar();
         
        JDesktopPane desktop=this.getDesktopPane();
        desktop.add(presoVW);
        presoVW.setVisible(true);
        presoVW.preencherCampos(presoModelo);
         
        }
         
        
         
         
    
        
    }//GEN-LAST:event_btEditarPresosActionPerformed

    private void btListarPresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btListarPresosActionPerformed
       listarOsCara();
    }//GEN-LAST:event_btListarPresosActionPerformed

    private void btCancelarListarPresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarListarPresoActionPerformed
        this.dispose();
    }//GEN-LAST:event_btCancelarListarPresoActionPerformed

    private void btExcluirPresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirPresosActionPerformed
        int selecionada=JTPreso.getSelectedRow();
        if(selecionada!=-1){
            PresoModel preso=new PresoModel();
            PresoController presoControl=new PresoController();
            preso.setIdPreso((Integer)JTPreso.getValueAt(selecionada,9));
            presoControl.excluir(preso);
            listarOsCara();
        
        }
    }//GEN-LAST:event_btExcluirPresosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTPreso;
    private javax.swing.JButton btCancelarListarPreso;
    private javax.swing.JButton btEditarPresos;
    private javax.swing.JButton btExcluirPresos;
    private javax.swing.JButton btListarPresos;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
