/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package TrabalhoFinal.view;

import TrabalhoFinal.controller.VisitaController;
import TrabalhoFinal.model.VisitaModel;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.List;

/**
 *
 * @author henri
 */
public class ListarVisitaView extends javax.swing.JInternalFrame {

    /**
     * Creates new form ListarVisitaView
     */
    public ListarVisitaView() {
        initComponents();
    }

    public void listarVisita() {
        List<VisitaModel> listarVisita = new VisitaController().listar();
        DefaultTableModel modelo = (DefaultTableModel) JTVisita.getModel();
        modelo.setRowCount(0);
        for (VisitaModel visita : listarVisita) {
            modelo.addRow(new Object[]{
                visita.getIdVisitante(),
                visita.getNomeVis(),
                visita.getTelefoneVis(),
                visita.getCpfVis(),
                visita.getDataNascimentoVis(),
                visita.getRgVis(),
                visita.getSexoVis(),
                visita.getNomeDoPreso(),
                visita.getParentesco(),
                visita.getDataVis(),
                visita.getHoraVis(),
                visita.getMotivoVis(),});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        JTVisita = new javax.swing.JTable();
        btListarVisita = new javax.swing.JButton();
        btEditarVisita = new javax.swing.JButton();
        btExcluirVisita = new javax.swing.JButton();
        btCancelarListarVisita = new javax.swing.JButton();

        JTVisita.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Nome", "Telefone", "CPF", "Data de Nascimento", "RG", "Sexo", "Nome do Preso", "Parentesco", "Hora da Visita", "Motivo da Visita", "Data da Visita"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JTVisita.setShowGrid(true);
        jScrollPane1.setViewportView(JTVisita);

        btListarVisita.setText("Listar Visita");
        btListarVisita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btListarVisitaActionPerformed(evt);
            }
        });

        btEditarVisita.setText("Editar Visita");
        btEditarVisita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarVisitaActionPerformed(evt);
            }
        });

        btExcluirVisita.setText("Excluir Visita");
        btExcluirVisita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirVisitaActionPerformed(evt);
            }
        });

        btCancelarListarVisita.setText("Cancelar");
        btCancelarListarVisita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarListarVisitaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 876, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btListarVisita)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 185, Short.MAX_VALUE)
                        .addComponent(btEditarVisita)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 157, Short.MAX_VALUE)
                        .addComponent(btExcluirVisita)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                        .addComponent(btCancelarListarVisita)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btCancelarListarVisita, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btListarVisita, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btEditarVisita, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btExcluirVisita, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(0, 212, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btListarVisitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btListarVisitaActionPerformed
        listarVisita();
    }//GEN-LAST:event_btListarVisitaActionPerformed

    private void btEditarVisitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarVisitaActionPerformed
        int selecionada = JTVisita.getSelectedRow();
        if (selecionada != -1) {
            VisitaModel visitaModel = new VisitaModel();

            visitaModel.setIdVisitante(Integer.parseInt(JTVisita.getValueAt(selecionada, 0).toString()));
            visitaModel.setNomeVis(JTVisita.getValueAt(selecionada, 1).toString());
            visitaModel.setTelefoneVis(JTVisita.getValueAt(selecionada, 2).toString());
            visitaModel.setCpfVis(JTVisita.getValueAt(selecionada, 3).toString());
            visitaModel.setDataNascimentoVis(JTVisita.getValueAt(selecionada, 4).toString());
            visitaModel.setRgVis(JTVisita.getValueAt(selecionada, 5).toString());
            visitaModel.setSexoVis(JTVisita.getValueAt(selecionada, 6).toString());
            visitaModel.setNomeDoPreso(JTVisita.getValueAt(selecionada, 7).toString());
            visitaModel.setParentesco(JTVisita.getValueAt(selecionada, 8).toString());
            visitaModel.setDataVis(JTVisita.getValueAt(selecionada, 9).toString());
            visitaModel.setHoraVis(JTVisita.getValueAt(selecionada, 10).toString());
            visitaModel.setMotivoVis(JTVisita.getValueAt(selecionada, 11).toString());

            VisitaView visitaView = new VisitaView();
            visitaView.ativarSalvar();
            JDesktopPane desktop = this.getDesktopPane();
            desktop.add(visitaView);
            visitaView.setVisible(true);
            visitaView.preencherCampos(visitaModel);
        }
    }//GEN-LAST:event_btEditarVisitaActionPerformed

    private void btExcluirVisitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirVisitaActionPerformed
        int selecionada = JTVisita.getSelectedRow();
        if (selecionada != -1) {
            VisitaModel visitaModel = new VisitaModel();
            VisitaController visitaController = new VisitaController();
            visitaModel.setIdVisitante((Integer) JTVisita.getValueAt(selecionada, 0));
            visitaController.excluir(visitaModel);
            listarVisita();
        }
    }//GEN-LAST:event_btExcluirVisitaActionPerformed

    private void btCancelarListarVisitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarListarVisitaActionPerformed
        this.dispose();
    }//GEN-LAST:event_btCancelarListarVisitaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTVisita;
    private javax.swing.JButton btCancelarListarVisita;
    private javax.swing.JButton btEditarVisita;
    private javax.swing.JButton btExcluirVisita;
    private javax.swing.JButton btListarVisita;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
