/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package TrabalhoFinal.view;

import TrabalhoFinal.controller.FuncionarioController;
import TrabalhoFinal.model.FuncionarioModel;
import java.util.List;
import javax.swing.JDesktopPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author diogo
 */
public class ListarFuncionarioView extends javax.swing.JInternalFrame {

    /**
     * Creates new form ListarFuncionarioView
     */
    public ListarFuncionarioView() {
        initComponents();
    }
    
    public void listarOsCara(){
    List<FuncionarioModel>listarFuncionario=new FuncionarioController().listar();
       DefaultTableModel modelo=(DefaultTableModel)JTFuncionario.getModel();
       modelo.setRowCount(0);
       for(FuncionarioModel funcionario: listarFuncionario){
       modelo.addRow(new Object[]{
       funcionario.getNomeFunc(),
       funcionario.getCpfFunc(),
       funcionario.getDataNascimentoFunc(),
       funcionario.getRG(),
       funcionario.getSexo(),
       funcionario.getCargo(),
       funcionario.getDataAdmissao(),
       funcionario.getEmail(),
       funcionario.getTelefone(),
       funcionario.getTurno(),
       funcionario.getId_func()
       });
}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btListarFuncionario = new javax.swing.JButton();
        btEditarFuncionario = new javax.swing.JButton();
        btExcluirFuncionario = new javax.swing.JButton();
        btCancelarListarFuncionario = new javax.swing.JButton();
        JSPListarFuncionario = new javax.swing.JScrollPane();
        JTFuncionario = new javax.swing.JTable();

        btListarFuncionario.setText("Listar Funcionarios");
        btListarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btListarFuncionarioActionPerformed(evt);
            }
        });

        btEditarFuncionario.setText("Editar Funcionarios");
        btEditarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarFuncionarioActionPerformed(evt);
            }
        });

        btExcluirFuncionario.setText("Excluir Funcionarios");
        btExcluirFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirFuncionarioActionPerformed(evt);
            }
        });

        btCancelarListarFuncionario.setText("Cancelar");
        btCancelarListarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarListarFuncionarioActionPerformed(evt);
            }
        });

        JSPListarFuncionario.setAutoscrolls(true);

        JTFuncionario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "CPF", "Data de nascimento", "RG", "Sexo", "Cargo", "Data de Admissao", "Email", "Telefone", "Turno", "Id"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JTFuncionario.setShowGrid(true);
        JSPListarFuncionario.setViewportView(JTFuncionario);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btListarFuncionario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addComponent(btEditarFuncionario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addComponent(btExcluirFuncionario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                .addComponent(btCancelarListarFuncionario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(JSPListarFuncionario, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btCancelarListarFuncionario, btEditarFuncionario, btExcluirFuncionario, btListarFuncionario});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JSPListarFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btCancelarListarFuncionario, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btListarFuncionario)
                        .addComponent(btEditarFuncionario)
                        .addComponent(btExcluirFuncionario)))
                .addGap(0, 249, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btListarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btListarFuncionarioActionPerformed
        listarOsCara();
    }//GEN-LAST:event_btListarFuncionarioActionPerformed

    private void btEditarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarFuncionarioActionPerformed
        int selecionada = JTFuncionario.getSelectedRow();
        if (selecionada != -1) {
            FuncionarioModel funcionarioModelo = new FuncionarioModel();

            funcionarioModelo.setNomeFunc(JTFuncionario.getValueAt(selecionada, 0).toString());
            funcionarioModelo.setCpfFunc(JTFuncionario.getValueAt(selecionada, 1).toString());
            funcionarioModelo.setDataNascimentoFunc(JTFuncionario.getValueAt(selecionada, 2).toString());
            funcionarioModelo.setRG(JTFuncionario.getValueAt(selecionada, 3).toString());
            funcionarioModelo.setSexo(JTFuncionario.getValueAt(selecionada, 4).toString());
            funcionarioModelo.setCargo(JTFuncionario.getValueAt(selecionada, 5).toString());
            funcionarioModelo.setDataAdmissao(JTFuncionario.getValueAt(selecionada, 6).toString());
            funcionarioModelo.setEmail(JTFuncionario.getValueAt(selecionada, 7).toString());
            funcionarioModelo.setTelefone(JTFuncionario.getValueAt(selecionada, 8).toString());
            funcionarioModelo.setTurno(JTFuncionario.getValueAt(selecionada, 9).toString());
            funcionarioModelo.setId_func(Integer.parseInt(JTFuncionario.getValueAt(selecionada, 10).toString()));
            FuncionarioView funcionarioVW = new FuncionarioView();
            funcionarioVW.ativarSalvar();
            JDesktopPane desktop = this.getDesktopPane();
            desktop.add(funcionarioVW);
            funcionarioVW.setVisible(true);
            funcionarioVW.preencherCampos(funcionarioModelo);

        }

    }//GEN-LAST:event_btEditarFuncionarioActionPerformed

    private void btExcluirFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirFuncionarioActionPerformed
        int selecionada = JTFuncionario.getSelectedRow();
        if (selecionada != -1) {
            FuncionarioModel funcionario = new FuncionarioModel();
            FuncionarioController presoControl = new FuncionarioController();
            funcionario.setId_func((Integer) JTFuncionario.getValueAt(selecionada, 10));
            presoControl.excluir(funcionario);
            listarOsCara();

        }
    }//GEN-LAST:event_btExcluirFuncionarioActionPerformed

    private void btCancelarListarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarListarFuncionarioActionPerformed
        this.dispose();
    }//GEN-LAST:event_btCancelarListarFuncionarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane JSPListarFuncionario;
    private javax.swing.JTable JTFuncionario;
    private javax.swing.JButton btCancelarListarFuncionario;
    private javax.swing.JButton btEditarFuncionario;
    private javax.swing.JButton btExcluirFuncionario;
    private javax.swing.JButton btListarFuncionario;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
