/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package TrabalhoFinal.view;

import TrabalhoFinal.controller.CelaController;
import TrabalhoFinal.controller.PresoController;
import TrabalhoFinal.model.CelaModel;
import TrabalhoFinal.model.PresoModel;
import java.awt.Image;
import java.util.List;
import javax.swing.*;

/**
 *
 * @author diogo
 */
public class PresoView extends javax.swing.JInternalFrame {

    private int idPresoAtual = -1;

    /**
     * Creates new form Preso1View
     */
    public PresoView() {
        initComponents();
        carregarCelasNoCombo();
        setResizable(false);
        ImageIcon icon = new ImageIcon(getClass().getResource("foto.png"));
        Image img = icon.getImage().getScaledInstance(160, 160, Image.SCALE_SMOOTH);
        btFotoPreso.setIcon(new ImageIcon(img));
        tfNome.setEnabled(false);
        tfCpf.setEnabled(false);
        tfDataNascimento.setEnabled(false);
        tfFiliacao.setEnabled(false);
        tfNaturalidade.setEnabled(false);
        tfCor.setEnabled(false);
        tfDataPrisao.setEnabled(false);
        tfPena.setEnabled(false);
        cbPresoCela.setEnabled(false);
        btSalvar.setEnabled(false);
        btLimpar.setEnabled(false);
        btSalvarAlt.setVisible(false);
    }

    private void carregarCelasNoCombo() {
        CelaController controller = new CelaController();
        List<CelaModel> celas = controller.buscarCelas();
        cbPresoCela.removeAllItems();

        for (CelaModel cela : celas) {
            cbPresoCela.addItem(cela);
            System.out.println("Celas carregadas: " + celas);

        }
    }

    public void ativarSalvar() {
        btSalvarAlt.setVisible(true);
        btSalvar.setVisible(false);
        btInserir.setVisible(false);
        tfNome.setEnabled(true);
        tfCpf.setEnabled(true);
        tfDataNascimento.setEnabled(true);
        tfFiliacao.setEnabled(true);
        tfNaturalidade.setEnabled(true);
        tfCor.setEnabled(true);
        tfDataPrisao.setEnabled(true);
        tfPena.setEnabled(true);
        cbPresoCela.setEnabled(true);
        btSalvar.setEnabled(true);
        btLimpar.setEnabled(true);
    }

    public void limparCampos() {

        tfNome.setText("");
        tfCpf.setText("");
        tfDataNascimento.setText("");
        cbPresoCela.setSelectedItem("");
        tfPena.setText("");
        tfFiliacao.setText("");
        tfNaturalidade.setText("");
        tfCor.setText("");
        tfDataPrisao.setText("");

    }

    private void selecionarCelaNoCombo(int idCela) {
        for (int i = 0; i < cbPresoCela.getItemCount(); i++) {
            CelaModel cela = cbPresoCela.getItemAt(i);
            if (cela.getNumero() == idCela) {
                cbPresoCela.setSelectedIndex(i);
                return;
            }
        }
    }

    public void preencherCampos(PresoModel preso) {

        tfNome.setText(preso.getNome());
        tfCpf.setText(preso.getCpf());
        tfDataNascimento.setText(preso.getDataNascimento());
        tfFiliacao.setText(preso.getFiliacao());
        tfNaturalidade.setText(preso.getNaturalidade());
        tfCor.setText(preso.getCor());
        tfDataPrisao.setText(preso.getDataEntrada());
        tfPena.setText(preso.getPena());
        selecionarCelaNoCombo(preso.getIdCela());
        idPresoAtual = preso.getIdPreso();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbNome = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        lbCpf = new javax.swing.JLabel();
        tfCpf = new javax.swing.JTextField();
        lbDataNascimento = new javax.swing.JLabel();
        tfDataNascimento = new javax.swing.JTextField();
        lbCela = new javax.swing.JLabel();
        lbPena = new javax.swing.JLabel();
        tfPena = new javax.swing.JTextField();
        btFotoPreso = new javax.swing.JButton();
        lbFiliacao = new javax.swing.JLabel();
        tfFiliacao = new javax.swing.JTextField();
        lbNaturaldiade = new javax.swing.JLabel();
        tfNaturalidade = new javax.swing.JTextField();
        lbCor = new javax.swing.JLabel();
        tfCor = new javax.swing.JTextField();
        lbDataPrisao = new javax.swing.JLabel();
        tfDataPrisao = new javax.swing.JTextField();
        lbCadastroFunc = new javax.swing.JLabel();
        cbPresoCela = new javax.swing.JComboBox<>();
        btInserir = new javax.swing.JButton();
        btSalvar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        btSalvarAlt = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(900, 623));

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel2.setText(" SISTEMA PENITENCIÁRIO ");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jLabel2.setOpaque(true);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        lbNome.setText("Nome:");

        tfNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomeActionPerformed(evt);
            }
        });

        lbCpf.setText("CPF:");

        tfCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCpfActionPerformed(evt);
            }
        });

        lbDataNascimento.setText("Data de Nascimento:");

        tfDataNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDataNascimentoActionPerformed(evt);
            }
        });

        lbCela.setText("Cela:");

        lbPena.setText("Pena:");

        tfPena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPenaActionPerformed(evt);
            }
        });

        btFotoPreso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TrabalhoFinal/view/foto.png"))); // NOI18N
        btFotoPreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFotoPresoActionPerformed(evt);
            }
        });

        lbFiliacao.setText("Filiação:");

        tfFiliacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfFiliacaoActionPerformed(evt);
            }
        });

        lbNaturaldiade.setText("Naturalidade:");

        lbCor.setText("Cor:");

        lbDataPrisao.setText("Data de Prisão");

        tfDataPrisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDataPrisaoActionPerformed(evt);
            }
        });

        lbCadastroFunc.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        lbCadastroFunc.setText("Cadastro de Preso");

        cbPresoCela.setModel(new javax.swing.DefaultComboBoxModel<CelaModel>());
        cbPresoCela.setSelectedItem(new javax.swing.DefaultComboBoxModel<CelaModel>());
        cbPresoCela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPresoCelaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbCadastroFunc))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(btFotoPreso, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lbPena)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfPena, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lbNaturaldiade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfNaturalidade))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lbFiliacao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfFiliacao))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lbDataNascimento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfDataNascimento))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(lbCpf)
                                .addGap(18, 18, 18)
                                .addComponent(tfCpf))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(lbNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lbCor)
                                .addGap(13, 13, 13)
                                .addComponent(tfCor))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lbDataPrisao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfDataPrisao))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lbCela)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbPresoCela, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(68, 68, 68))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(lbCadastroFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbNome)
                            .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbCpf)
                            .addComponent(tfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbDataNascimento)
                            .addComponent(tfDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbFiliacao)
                            .addComponent(tfFiliacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbNaturaldiade)
                            .addComponent(tfNaturalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btFotoPreso, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCor)
                    .addComponent(tfCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDataPrisao)
                    .addComponent(tfDataPrisao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPena)
                    .addComponent(tfPena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbCela)
                    .addComponent(cbPresoCela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        btInserir.setText("Inserir");
        btInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInserirActionPerformed(evt);
            }
        });

        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        btSalvarAlt.setText("Salvar alterações");
        btSalvarAlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarAltActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(262, 262, 262)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(130, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btInserir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btLimpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btSalvarAlt)))
                .addContainerGap(136, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btInserir)
                    .addComponent(btSalvar)
                    .addComponent(btLimpar)
                    .addComponent(btCancelar)
                    .addComponent(btSalvarAlt))
                .addContainerGap(109, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomeActionPerformed

    private void tfCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCpfActionPerformed

    private void tfDataNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDataNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDataNascimentoActionPerformed

    private void tfPenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPenaActionPerformed

    private void tfFiliacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfFiliacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfFiliacaoActionPerformed

    private void btInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInserirActionPerformed
        tfNome.setEnabled(true);
        tfCpf.setEnabled(true);
        tfDataNascimento.setEnabled(true);
        tfFiliacao.setEnabled(true);
        tfNaturalidade.setEnabled(true);
        tfCor.setEnabled(true);
        tfDataPrisao.setEnabled(true);
        tfPena.setEnabled(true);
        cbPresoCela.setEnabled(true);
        btSalvar.setEnabled(true);
        btLimpar.setEnabled(true);
        btInserir.setEnabled(false);
    }//GEN-LAST:event_btInserirActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed

        this.dispose();
    }//GEN-LAST:event_btCancelarActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        limparCampos();
    }//GEN-LAST:event_btLimparActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        PresoModel preso = new PresoModel();

        CelaModel celaSelecionada = (CelaModel) cbPresoCela.getSelectedItem();
        if (celaSelecionada != null) {
            preso.setIdCela(celaSelecionada.getNumero()); 
        } 

        preso.setNome(tfNome.getText());
        preso.setDataNascimento(tfDataNascimento.getText());
        preso.setDataEntrada(tfDataPrisao.getText());
        preso.setCpf(tfCpf.getText());
        preso.setPena(tfPena.getText());
        preso.setFiliacao(tfFiliacao.getText());
        preso.setNaturalidade(tfNaturalidade.getText());
        preso.setCor(tfCor.getText());

        PresoController presoControl = new PresoController();
        boolean sucesso = presoControl.inserir(preso);

        if (sucesso) {
            JOptionPane.showMessageDialog(this, "Preso inserido com sucesso!");
            limparCampos();

            tfNome.setEnabled(false);
            tfCpf.setEnabled(false);
            tfDataNascimento.setEnabled(false);
            tfFiliacao.setEnabled(false);
            tfNaturalidade.setEnabled(false);
            tfCor.setEnabled(false);
            tfDataPrisao.setEnabled(false);
            tfPena.setEnabled(false);
            cbPresoCela.setEnabled(false);
            btSalvar.setEnabled(false);
            btLimpar.setEnabled(false);
            btInserir.setEnabled(true);
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao inserir preso.");
        }


    }//GEN-LAST:event_btSalvarActionPerformed

    private void btFotoPresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFotoPresoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btFotoPresoActionPerformed

    private void tfDataPrisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDataPrisaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDataPrisaoActionPerformed

    private void btSalvarAltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarAltActionPerformed
        PresoModel preso = new PresoModel();
        preso.setIdPreso(this.idPresoAtual);
        preso.setIdCela(Integer.parseInt(cbPresoCela.getSelectedItem().toString()));
        preso.setNome(tfNome.getText());
        preso.setDataNascimento(tfDataNascimento.getText());
        preso.setDataEntrada(tfDataPrisao.getText());
        preso.setCpf(tfCpf.getText());
        preso.setPena(tfPena.getText());
        preso.setFiliacao(tfFiliacao.getText());
        preso.setNaturalidade(tfNaturalidade.getText());
        preso.setCor(tfCor.getText());
        PresoController presoControl = new PresoController();
        presoControl.atualizar(preso);
        limparCampos();
        JOptionPane.showMessageDialog(this, "Preso editado com sucesso!");
        this.dispose();
    }//GEN-LAST:event_btSalvarAltActionPerformed

    private void cbPresoCelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPresoCelaActionPerformed

        CelaModel celaSelecionada = (CelaModel) cbPresoCela.getSelectedItem();
        if (celaSelecionada != null) {
            int numero = celaSelecionada.getNumero();
        }
    }//GEN-LAST:event_cbPresoCelaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btFotoPreso;
    private javax.swing.JButton btInserir;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btSalvar;
    private javax.swing.JButton btSalvarAlt;
    private javax.swing.JComboBox<CelaModel> cbPresoCela;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbCadastroFunc;
    private javax.swing.JLabel lbCela;
    private javax.swing.JLabel lbCor;
    private javax.swing.JLabel lbCpf;
    private javax.swing.JLabel lbDataNascimento;
    private javax.swing.JLabel lbDataPrisao;
    private javax.swing.JLabel lbFiliacao;
    private javax.swing.JLabel lbNaturaldiade;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbPena;
    private javax.swing.JTextField tfCor;
    private javax.swing.JTextField tfCpf;
    private javax.swing.JTextField tfDataNascimento;
    private javax.swing.JTextField tfDataPrisao;
    private javax.swing.JTextField tfFiliacao;
    private javax.swing.JTextField tfNaturalidade;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfPena;
    // End of variables declaration//GEN-END:variables
}
