/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package TrabalhoFinal.view;

import TrabalhoFinal.controller.VisitaController;
import TrabalhoFinal.model.VisitaModel;

/**
 *
 * @author henri
 */
public class VisitaView extends javax.swing.JInternalFrame {

    /**
     * Creates new form VisitanteView
     */
    public VisitaView() {
        initComponents();

        tfNomeVis.setEnabled(false);
        tfTelefoneVis.setEnabled(false);
        tfCpfVis.setEnabled(false);
        tfDataNascimentoVis.setEnabled(false);
        tfRGVis.setEnabled(false);
        rbMasculino.setEnabled(false);
        rbFeminino.setEnabled(false);
        tfNomeDoPreso.setEnabled(false);
        tfParentescoVis.setEnabled(false);
        tfDataVis.setEnabled(false);
        tfHoraVis.setEnabled(false);
        tfMotivoVis.setEnabled(false);
        btSalvarVis.setEnabled(false);
        btLimparVis.setEnabled(false);
        btSalvarAltVis.setVisible(false);
    }

    public void limparCampos() {
        tfNomeVis.setText("");
        tfTelefoneVis.setText("");
        tfCpfVis.setText("");
        tfDataNascimentoVis.setText("");
        tfRGVis.setText("");
        rbMasculino.setSelected(false);
        rbFeminino.setSelected(false);
        tfNomeDoPreso.setText("");
        tfParentescoVis.setText("");
        tfDataVis.setText("");
        tfHoraVis.setText("");
        tfMotivoVis.setText("");
    }

    int idVisitaAtual = 0;

    public void preencherCampos(VisitaModel visitante) {
        idVisitaAtual = visitante.getIdVisitante();
        String sexo = visitante.getSexoVis();
        tfNomeVis.setText(visitante.getNomeVis());
        tfTelefoneVis.setText(visitante.getTelefoneVis());
        tfCpfVis.setText(visitante.getCpfVis());
        tfRGVis.setText(visitante.getRgVis());
        tfDataNascimentoVis.setText(visitante.getDataNascimentoVis());
        if (sexo.equals("Masculino")) {
            rbMasculino.setSelected(true);
        } else if (sexo.equals("Feminino")) {
            rbFeminino.setSelected(true);
        }

        tfNomeDoPreso.setText(visitante.getNomeDoPreso());
        tfParentescoVis.setText(visitante.getParentesco());
        tfDataVis.setText(visitante.getDataVis());
        tfHoraVis.setText(visitante.getHoraVis());
        tfMotivoVis.setText(visitante.getMotivoVis());

    }

    public void ativarSalvar() {

        btSalvarAltVis.setVisible(true);
        btSalvarVis.setEnabled(false);
        btInserirVis.setEnabled(false);
        tfNomeVis.setEnabled(true);
        tfTelefoneVis.setEnabled(true);
        tfCpfVis.setEnabled(true);
        tfDataNascimentoVis.setEnabled(true);
        tfRGVis.setEnabled(true);
        rbMasculino.setEnabled(true);
        rbFeminino.setEnabled(true);
        tfNomeDoPreso.setEnabled(true);
        tfParentescoVis.setEnabled(true);
        tfDataVis.setEnabled(true);
        tfHoraVis.setEnabled(true);
        tfMotivoVis.setEnabled(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbNomeVis = new javax.swing.JLabel();
        tfNomeVis = new javax.swing.JTextField();
        lbCpfVisitante = new javax.swing.JLabel();
        tfCpfVis = new javax.swing.JTextField();
        lbDataNascimentoVisitante = new javax.swing.JLabel();
        tfDataNascimentoVis = new javax.swing.JTextField();
        lbtelefoneVisitante = new javax.swing.JLabel();
        tfTelefoneVis = new javax.swing.JTextField();
        lbDataVisita = new javax.swing.JLabel();
        tfDataVis = new javax.swing.JTextField();
        btFotoPreso = new javax.swing.JButton();
        lbRGVisitante = new javax.swing.JLabel();
        tfRGVis = new javax.swing.JTextField();
        lbSexoVisitante = new javax.swing.JLabel();
        lbParentescoVisitante = new javax.swing.JLabel();
        tfParentescoVis = new javax.swing.JTextField();
        lbNomeDoPreso = new javax.swing.JLabel();
        tfNomeDoPreso = new javax.swing.JTextField();
        rbMasculino = new javax.swing.JRadioButton();
        rbFeminino = new javax.swing.JRadioButton();
        lbCadastroVisita = new javax.swing.JLabel();
        lbHoraVisita = new javax.swing.JLabel();
        tfHoraVis = new javax.swing.JTextField();
        lbMotivoVisita = new javax.swing.JLabel();
        tfMotivoVis = new javax.swing.JTextField();
        btInserirVis = new javax.swing.JButton();
        btSalvarVis = new javax.swing.JButton();
        btCancelarVis = new javax.swing.JButton();
        btLimparVis = new javax.swing.JButton();
        btSalvarAltVis = new javax.swing.JButton();

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel3.setText(" SISTEMA PENITENCIÁRIO ");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jLabel3.setOpaque(true);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        lbNomeVis.setText("Nome:");

        tfNomeVis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomeVisActionPerformed(evt);
            }
        });

        lbCpfVisitante.setText("CPF:");

        tfCpfVis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCpfVisActionPerformed(evt);
            }
        });

        lbDataNascimentoVisitante.setText("Data de Nascimento:");

        tfDataNascimentoVis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDataNascimentoVisActionPerformed(evt);
            }
        });

        lbtelefoneVisitante.setText("Telefone");

        tfTelefoneVis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTelefoneVisActionPerformed(evt);
            }
        });

        lbDataVisita.setText("Data da Visita:");

        tfDataVis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDataVisActionPerformed(evt);
            }
        });

        btFotoPreso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TrabalhoFinal/view/foto.png"))); // NOI18N
        btFotoPreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFotoPresoActionPerformed(evt);
            }
        });

        lbRGVisitante.setText("RG:");

        tfRGVis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfRGVisActionPerformed(evt);
            }
        });

        lbSexoVisitante.setText("Sexo:");

        lbParentescoVisitante.setText("Parentesco:");

        tfParentescoVis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfParentescoVisActionPerformed(evt);
            }
        });

        lbNomeDoPreso.setText("Nome do Preso:");

        tfNomeDoPreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomeDoPresoActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbMasculino);
        rbMasculino.setText("Masculino");
        rbMasculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMasculinoActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbFeminino);
        rbFeminino.setText("Feminino");

        lbCadastroVisita.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        lbCadastroVisita.setText("Cadastro de Visita");

        lbHoraVisita.setText("Horário da Visita:");

        tfHoraVis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfHoraVisActionPerformed(evt);
            }
        });

        lbMotivoVisita.setText("Motivo da Visita:");

        tfMotivoVis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMotivoVisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btFotoPreso, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbMotivoVisita)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfMotivoVis))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbNomeDoPreso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfNomeDoPreso, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbParentescoVisitante)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfParentescoVis, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(lbCadastroVisita)
                            .addGap(42, 42, 42))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lbDataNascimentoVisitante)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfDataNascimentoVis))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(lbCpfVisitante)
                                .addGap(18, 18, 18)
                                .addComponent(tfCpfVis))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lbNomeVis)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfNomeVis, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(lbRGVisitante)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfRGVis, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbtelefoneVisitante)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfTelefoneVis, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbSexoVisitante)
                        .addGap(18, 18, 18)
                        .addComponent(rbMasculino)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbFeminino))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lbHoraVisita)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfHoraVis))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lbDataVisita)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfDataVis, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(79, 79, 79))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lbCadastroVisita, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbNomeVis)
                            .addComponent(tfNomeVis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfTelefoneVis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbtelefoneVisitante))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfCpfVis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbCpfVisitante)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btFotoPreso, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDataNascimentoVisitante)
                    .addComponent(tfDataNascimentoVis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfRGVis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbRGVisitante))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSexoVisitante)
                    .addComponent(rbMasculino)
                    .addComponent(rbFeminino))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNomeDoPreso)
                    .addComponent(tfNomeDoPreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbParentescoVisitante)
                    .addComponent(tfParentescoVis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDataVisita)
                    .addComponent(tfDataVis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbHoraVisita)
                    .addComponent(tfHoraVis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMotivoVisita)
                    .addComponent(tfMotivoVis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btInserirVis.setText("Inserir");
        btInserirVis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInserirVisActionPerformed(evt);
            }
        });

        btSalvarVis.setText("Salvar");
        btSalvarVis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarVisActionPerformed(evt);
            }
        });

        btCancelarVis.setText("Cancelar");
        btCancelarVis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarVisActionPerformed(evt);
            }
        });

        btLimparVis.setText("Limpar");
        btLimparVis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparVisActionPerformed(evt);
            }
        });

        btSalvarAltVis.setText("Salvar Alterações");
        btSalvarAltVis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarAltVisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(168, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(239, 239, 239))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btInserirVis)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                        .addComponent(btSalvarVis)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                        .addComponent(btLimparVis)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                        .addComponent(btCancelarVis)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                        .addComponent(btSalvarAltVis)
                        .addContainerGap(100, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(167, 167, 167))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btSalvarAltVis)
                    .addComponent(btInserirVis)
                    .addComponent(btSalvarVis)
                    .addComponent(btCancelarVis)
                    .addComponent(btLimparVis))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbMasculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMasculinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbMasculinoActionPerformed

    private void tfNomeDoPresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomeDoPresoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomeDoPresoActionPerformed

    private void tfRGVisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfRGVisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfRGVisActionPerformed

    private void btFotoPresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFotoPresoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btFotoPresoActionPerformed

    private void tfDataVisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDataVisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDataVisActionPerformed

    private void tfTelefoneVisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTelefoneVisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTelefoneVisActionPerformed

    private void tfDataNascimentoVisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDataNascimentoVisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDataNascimentoVisActionPerformed

    private void tfCpfVisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCpfVisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCpfVisActionPerformed

    private void tfNomeVisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomeVisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomeVisActionPerformed

    private void tfHoraVisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfHoraVisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfHoraVisActionPerformed

    private void tfMotivoVisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMotivoVisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMotivoVisActionPerformed

    private void btInserirVisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInserirVisActionPerformed

        btSalvarVis.setEnabled(true);
        btInserirVis.setEnabled(false);
        tfNomeVis.setEnabled(true);
        tfTelefoneVis.setEnabled(true);
        tfCpfVis.setEnabled(true);
        tfDataNascimentoVis.setEnabled(true);
        tfRGVis.setEnabled(true);
        rbMasculino.setEnabled(true);
        rbFeminino.setEnabled(true);
        tfNomeDoPreso.setEnabled(true);
        tfParentescoVis.setEnabled(true);
        tfDataVis.setEnabled(true);
        tfHoraVis.setEnabled(true);
        tfMotivoVis.setEnabled(true);
    }//GEN-LAST:event_btInserirVisActionPerformed

    private void btSalvarVisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarVisActionPerformed

        VisitaModel visita = new VisitaModel();
        String sexo = "";

        visita.setNomeVis(tfNomeVis.getText());
        visita.setTelefoneVis(tfTelefoneVis.getText());
        visita.setCpfVis(tfCpfVis.getText());
        visita.setDataNascimentoVis(tfDataNascimentoVis.getText());
        visita.setRgVis(tfRGVis.getText());

        if (rbMasculino.isSelected()) {
            sexo = rbMasculino.getText();
        } else {
            sexo = rbFeminino.getText();
        }

        visita.setSexoVis(sexo);

        visita.setNomeDoPreso(tfNomeDoPreso.getText());
        visita.setParentesco(tfParentescoVis.getText());
        visita.setDataVis(tfDataVis.getText());
        visita.setHoraVis(tfHoraVis.getText());
        visita.setMotivoVis(tfMotivoVis.getText());

        VisitaController visitaController = new VisitaController();
        visitaController.inserir(visita);
        limparCampos();

        tfNomeVis.setEnabled(false);
        tfTelefoneVis.setEnabled(false);
        tfCpfVis.setEnabled(false);
        tfDataNascimentoVis.setEnabled(false);
        tfRGVis.setEnabled(false);
        rbMasculino.setEnabled(false);
        rbFeminino.setEnabled(false);
        tfNomeDoPreso.setEnabled(false);
        tfParentescoVis.setEnabled(false);
        tfDataVis.setEnabled(false);
        tfHoraVis.setEnabled(false);
        tfMotivoVis.setEnabled(false);
        btSalvarVis.setEnabled(false);
        btLimparVis.setEnabled(false);
        btInserirVis.setEnabled(true);

    }//GEN-LAST:event_btSalvarVisActionPerformed

    private void btCancelarVisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarVisActionPerformed
        this.dispose();
    }//GEN-LAST:event_btCancelarVisActionPerformed

    private void btLimparVisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparVisActionPerformed
        limparCampos();
    }//GEN-LAST:event_btLimparVisActionPerformed

    private void btSalvarAltVisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarAltVisActionPerformed
        String sexo = "";

        VisitaModel visita = new VisitaModel();
        visita.setIdVisitante(this.idVisitaAtual);
        visita.setNomeVis(tfNomeVis.getText());
        visita.setTelefoneVis(tfTelefoneVis.getText());
        visita.setCpfVis(tfCpfVis.getText());
        visita.setDataNascimentoVis(tfDataVis.getText());
        visita.setRgVis(tfRGVis.getText());

        if (rbMasculino.isSelected()) {
            sexo = rbMasculino.getText();
        } else {
            sexo = rbFeminino.getText();
        }

        visita.setSexoVis(sexo);

        visita.setNomeDoPreso(tfNomeDoPreso.getText());
        visita.setParentesco(tfParentescoVis.getText());
        visita.setDataVis(tfDataVis.getText());
        visita.setHoraVis(tfHoraVis.getText());
        visita.setMotivoVis(tfMotivoVis.getText());

        VisitaController visitaController = new VisitaController();
        visitaController.atualizar(visita);
        limparCampos();

        this.dispose();

    }//GEN-LAST:event_btSalvarAltVisActionPerformed

    private void tfParentescoVisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfParentescoVisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfParentescoVisActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelarVis;
    private javax.swing.JButton btFotoPreso;
    private javax.swing.JButton btInserirVis;
    private javax.swing.JButton btLimparVis;
    private javax.swing.JButton btSalvarAltVis;
    private javax.swing.JButton btSalvarVis;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbCadastroVisita;
    private javax.swing.JLabel lbCpfVisitante;
    private javax.swing.JLabel lbDataNascimentoVisitante;
    private javax.swing.JLabel lbDataVisita;
    private javax.swing.JLabel lbHoraVisita;
    private javax.swing.JLabel lbMotivoVisita;
    private javax.swing.JLabel lbNomeDoPreso;
    private javax.swing.JLabel lbNomeVis;
    private javax.swing.JLabel lbParentescoVisitante;
    private javax.swing.JLabel lbRGVisitante;
    private javax.swing.JLabel lbSexoVisitante;
    private javax.swing.JLabel lbtelefoneVisitante;
    private javax.swing.JRadioButton rbFeminino;
    private javax.swing.JRadioButton rbMasculino;
    private javax.swing.JTextField tfCpfVis;
    private javax.swing.JTextField tfDataNascimentoVis;
    private javax.swing.JTextField tfDataVis;
    private javax.swing.JTextField tfHoraVis;
    private javax.swing.JTextField tfMotivoVis;
    private javax.swing.JTextField tfNomeDoPreso;
    private javax.swing.JTextField tfNomeVis;
    private javax.swing.JTextField tfParentescoVis;
    private javax.swing.JTextField tfRGVis;
    private javax.swing.JTextField tfTelefoneVis;
    // End of variables declaration//GEN-END:variables
}
